#!/bin/bash
#setting php-cgi.exe
phpCGI='C:/xampp/php/php-cgi.exe'

#setting autoUploadWithGit path
autoUploadPath='D:/git/AutoUploadWithGit/action.php'

function showHelp(){
    echo -e ""
    echo -e "The most commonly used git-sftp command are:"
    echo -e "  \e[1;37m[-help]\e[0;37m     Lists available subcommands and some concept guides"
    echo -e "  \e[1;37m[-def]\e[0;37m      Show default between commits, commit and working tree"
    echo -e "  \e[1;37m[-p file]\e[0;37m   Upload file from working tree"
    echo -e "  \e[1;37m[<commit> <commit>]\e[0;37m   Upload file between commits, commit and working tree"
    echo -e ""
}

function showDefault(){
    echo -e ""
    echo -e "\e[1;37m[1] - git diff --name-only\e[0;32m"
    resultString=$(git diff --name-only)
    echo -e "\e[0;32m$resultString"
    echo -e ""
    
    echo -e "\e[1;37m[2] - git diff --name-only HEAD\e[0;32m"
    resultString=$(git diff --name-only HEAD)
    echo -e "\e[0;32m$resultString"
    
    echo -e ""
    echo -e "\e[1;37m[3] - git diff --name-only HEAD HEAD^\e[0;32m"
    resultString=$(git diff --name-only HEAD HEAD^)
    echo -e "\e[0;32m$resultString"
    
    echo -e ""
    echo -e "\e[1;37m[4] - git diff --name-only HEAD^ HEAD^^\e[0;32m"
    resultString=$(git diff --name-only HEAD^ HEAD^^)
    echo -e "\e[0;32m$resultString"
    echo -e ""
}

if [ "$arg_cmd1" == "-help" ]; then
    showHelp
elif [ "$arg_cmd1" == "-def" ]; then
    showDefault
    echo -e "\e[1;37m"
    read -p "plz input> " inputCommand
    if [ "$inputCommand" = "1" ]; then
        arg_cmd2=''
        arg_cmd3=''
    elif [ "$inputCommand" = "2" ]; then
        arg_cmd2='HEAD'
        arg_cmd3=''
    elif [ "$inputCommand" = "3" ]; then
        arg_cmd2='HEAD'
        arg_cmd3='HEAD^'
    elif [ "$inputCommand" = "4" ]; then
        arg_cmd2='HEAD^'
        arg_cmd3='HEAD^^'
    else
        exit 0
    fi
    resultString=$(git diff --name-only $arg_cmd2 $arg_cmd3)
elif [ "$arg_cmd1" == "-p" ]; then
    resultString=$arg_file
else
    resultString=$(git diff --name-only $arg_cmd2 $arg_cmd3)
fi


if [ "$resultString" == "" ]; then
    echo -e ""
    echo -e "\e[1;37mNot found files.\e[0;37m" 
    exit 0
fi

echo -e ""
echo -e ""
echo -e "========================"
echo -e "\e[1;37mUpload files:"
echo -e ""

count=1
resultStringArr[0]=''
for i in $resultString
do
    echo -e "\e[0;32m[$count] - $i"
    resultStringArr[$count]=$i
    count=$(($count+1))
done

echo -e "\e[0;37m========================"
echo -e ""
read -p "Are you continue to upload? (y/s/n):" uploadCommand
echo -e ""

dirname=$(basename `pwd`)

if [ "$uploadCommand" == "y" -o "$uploadCommand" == "Y" ]; then
    echo $resultString | "$phpCGI" "$autoUploadPath" upload inputBySFTP "$arg_env-$dirname" $dirname
    echo -e ""
elif [ "$uploadCommand" == "s" ]; then
    read -p "Enter upload to numbers ( ex: 1 3 4 5 ) : " uploadCommand
    IFS=' ' read -r -a array <<< "$uploadCommand"
    resultString=''
    for element in "${array[@]}"
    do
        resultString="$resultString ${resultStringArr[$element]}"
    done
    echo "$resultString" | "$phpCGI" "$autoUploadPath" upload inputBySFTP "$arg_env-$dirname" $dirname
else
    echo -e ""
    exit 0
fi